import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:pinpoint/app/constants.dart';
import 'package:pinpoint/features/map/domain/map_models.dart';

/// Generates shareable route PDF documents on device.
class RoutePdfService {
  Future<Uint8List> generate({
    required PlannedRoute route,
    required String originLabel,
    required String destinationLabel,
  }) async {
    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Text('PINPOINT Route Summary', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.Text('${AppConstants.cityName} • ${DateTime.now().toLocal()}'),
          pw.SizedBox(height: 16),
          pw.Text('From: $originLabel'),
          pw.Text('To: $destinationLabel'),
          pw.SizedBox(height: 12),
          pw.Text('Distance: ${route.distanceLabel}'),
          pw.Text('Duration: ${route.durationLabel}'),
          pw.Text('Estimated fare: PHP ${route.estimatedFare.toStringAsFixed(2)}'),
          pw.SizedBox(height: 16),
          pw.Text('Directions', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          ...route.steps.map(
            (step) => pw.Bullet(
              text: '${step.instruction} (${step.durationLabel})',
            ),
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by PINPOINT — Navigate Smarter. Travel Better.',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
        ],
      ),
    );
    return doc.save();
  }
}
